export const DiagnosticCode = {
  FILE_READ_FAILED: "FILE_READ_FAILED",
  FILE_TOO_LARGE: "FILE_TOO_LARGE",
  REPOSITORY_FILE_LIMIT_REACHED: "REPOSITORY_FILE_LIMIT_REACHED",
  REPOSITORY_SIZE_LIMIT_REACHED: "REPOSITORY_SIZE_LIMIT_REACHED",
  SENSITIVE_FILE_SKIPPED: "SENSITIVE_FILE_SKIPPED",
  BINARY_FILE_SKIPPED: "BINARY_FILE_SKIPPED",
  MANIFEST_PARSE_FAILED: "MANIFEST_PARSE_FAILED",
  SYMLINK_SKIPPED: "SYMLINK_SKIPPED",
  PERMISSION_DENIED: "PERMISSION_DENIED",
  UNKNOWN_FILE_TYPE: "UNKNOWN_FILE_TYPE",
  PACKAGE_MANAGER_CONFLICT: "PACKAGE_MANAGER_CONFLICT",
  GITIGNORE_READ_FAILED: "GITIGNORE_READ_FAILED",
  SOURCE_PARSE_FAILED: "SOURCE_PARSE_FAILED",
  SOURCE_SYNTAX_ERROR: "SOURCE_SYNTAX_ERROR",
  UNSUPPORTED_PARSER_LANGUAGE: "UNSUPPORTED_PARSER_LANGUAGE",
  SOURCE_READ_FAILED: "SOURCE_READ_FAILED",
  SOURCE_TOO_LARGE_FOR_PARSER: "SOURCE_TOO_LARGE_FOR_PARSER",
} as const;

export type DiagnosticCode = (typeof DiagnosticCode)[keyof typeof DiagnosticCode];
